### ISSUE TITLE
Prepare learnr tutorials

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#451]
Prepare 

https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials

for the upcoming semester.

**TODOs:**

- [x] Move from days to topics (as we did with slides)
- [x] Put new video links
- [x] Check/adapt study goals 
- [x] Check/adapt multiple choice questions 
- [x] Check coding questions and adapt to mlr3 (See #443)
- [x] Upload to shinyapps.io
- [x] Link on website

**Comment by HeidiSeibold** [comment]
## ml-basics

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## supervised-regression 

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## supervised-classification

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## evaluation

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## trees

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## forests

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## tuning

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3 

## nested-resampling

- [ ] Move from days to topics (as we did with slides)
- [ ] Put new video links
- [ ] Check/adapt study goals 
- [ ] Check/adapt multiple choice questions 
- [ ] Check coding questions and adapt to mlr3

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/evaluation is ready for converting to mlr3.

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/ml-basics is ready for converting to mlr3

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/supervised-regression is ready for converting to mlr3

Try to get `ml-basics` and `supervised-regression` ready first as it is day 1 and @fabian-s could then maybe check if we did a good job :wink:

**Comment by tpielok** [comment]
`ml-basics` is done ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/27))

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/trees is ready for converting to mlr3.

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/forests is ready for converting to mlr3.

**Comment by tpielok** [comment]
`supervised-regression` is done ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/28)), but we should wait with the merge till plotLearnerPrediction is implemented (you can follow the current progress [here](https://github.com/mlr-org/mlr3viz/pull/11))

**Comment by fabian-s** [comment]
thx! please ping again re `supervised-regression` once plotLearnerPrediction is live.

**Comment by tpielok** [comment]
`trees` is done ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/29)) and also waiting for plotLearnerPrediction.

**Comment by tpielok** [comment]
`random forest` is done ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/30)) and also waiting for plotLearnerPrediction.

**Comment by tpielok** [comment]
`evaluation` is done ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/26)) and also waiting for plot_learner_prediction.

**Comment by tpielok** [comment]
`supervised-regression`, `trees`, `random forest`, `evaluation` are ready to merge

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/supervised-classification is ready for converting to mlr3.

**Comment by tpielok** [comment]
`supervised classification` is done. ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/33))

**Comment by HeidiSeibold** [comment]
@tpielok https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/tree/refactoring-w1920/tuning is ready for converting to mlr3

**Comment by tpielok** [comment]
`tuning` is done. ([PR](https://github.com/compstat-lmu/lecture_i2ml_learnr_tutorials/pull/34))
